// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mivshliotqsuwonmpjem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pdnNobGlvdHFzdXdvbm1wamVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTQwOTQsImV4cCI6MjA2NzY5MDA5NH0.CtTdtJQgsffI09_rbpiLKwwbAbTd6N7wHqbhRzo4J4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
